// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpH93ptJFcRhovVt00Lu__l9Fz4bF2R0o',
    appId: '1:22071167419:web:488e128b289d5e02211c9e',
    messagingSenderId: '22071167419',
    projectId: 'rentify-b6e51',
    authDomain: 'rentify-b6e51.firebaseapp.com',
    storageBucket: 'rentify-b6e51.firebasestorage.app',
    measurementId: 'G-D5YGHCEVYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE6ZF3g57BO3FCcT-C6vun9km94YdOMWs',
    appId: '1:22071167419:android:558147854fbe4b79211c9e',
    messagingSenderId: '22071167419',
    projectId: 'rentify-b6e51',
    storageBucket: 'rentify-b6e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrQYJg98WyxINZCpRYCDCrql-sK7KdSI',
    appId: '1:202026031113:ios:9c1d3c13988048a12d40d8',
    messagingSenderId: '202026031113',
    projectId: 'fashionstore-1b406',
    storageBucket: 'fashionstore-1b406.firebasestorage.app',
    iosBundleId: 'com.rentify.rentify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrQYJg98WyxINZCpRYCDCrql-sK7KdSI',
    appId: '1:202026031113:ios:9c1d3c13988048a12d40d8',
    messagingSenderId: '202026031113',
    projectId: 'fashionstore-1b406',
    storageBucket: 'fashionstore-1b406.firebasestorage.app',
    iosBundleId: 'com.rentify.rentify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpH93ptJFcRhovVt00Lu__l9Fz4bF2R0o',
    appId: '1:22071167419:web:180b2449b92ec0e8211c9e',
    messagingSenderId: '22071167419',
    projectId: 'rentify-b6e51',
    authDomain: 'rentify-b6e51.firebaseapp.com',
    storageBucket: 'rentify-b6e51.firebasestorage.app',
    measurementId: 'G-98TSVKK3YM',
  );

}